# Generated by Django 4.2.5 on 2023-10-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_product_pricce_product_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_color',
            field=models.CharField(default='nil', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='product_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'XL'), ('XXL', 'XXL')], default='nil', max_length=50),
        ),
    ]
