# Generated by Django 4.2.5 on 2023-10-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productcolor_productsize_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
