# Generated by Django 4.2.5 on 2023-09-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(default=0, max_length=100, unique=True),
        ),
    ]
