# Generated by Django 4.2.5 on 2023-10-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='item_color',
            field=models.CharField(default='choose', max_length=50),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='item_size',
            field=models.CharField(default='choose', max_length=50),
        ),
    ]
