# Generated by Django 4.2.5 on 2023-10-08 04:41

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderproduct_color_orderproduct_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='color',
            field=models.CharField(blank=True, verbose_name=store.models.ProductColor),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='size',
            field=models.CharField(blank=True, verbose_name=store.models.ProductSize),
        ),
    ]
